name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      env: 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
      run: ./gradlew build

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 127.0.0.1:123456/my-image-name:$(date +%s)

    - name: setup ssh connection
      run: |
        echo "${{ secrets.BACKEND_SSH_KEY }}" > $(pwd)/private_key
        chmod 600 $(pwd)/private_key
        ssh -o "IdentitiesOnly=yes" -i $(pwd)/private_key -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -M -S server-socket -fnNT -L 12346:${{ secrets.BACKEND_SSH_HOST }}:5000 ${{ secrets.BACKEND_SSH_USERNAME }}@${{ secrets.BACKEND_SSH_HOST }}

    - name: Push the docker image
      run: docker push 127.0.0.1:123456/my-image-name:$(date +%s)

    - name: teardown
      if: always()
      run: |
        ssh -S server-socket -O exit ${{ secrets.BACKEND_SSH_USERNAME }}@${{ secrets.BACKEND_SSH_HOST }}
